### ISSUE TITLE
Default values for precision of analog input/output records

### ISSUE THREAD

**Issue by klauer** [slaclab/epics-ek9000#30]
## Issue

EL3062 records such as:

https://github.com/slaclab/epics-ek9000/blob/248a4a1cfafebd960e30bd983e4b2ef72ff36a17/ek9000App/Db/EL3062.template#L1

Have `.PREC` default to 0.
Clients like Grafana take a precision setting of 0 to mean "display as an integer" - which is rarely what we want.

## Path forward

For now, `.PREC` appears to be autosaved and can be customized by the user without much issue - on a channel-by-channel basis.

### Fields

* I think it might be wise to set a sensible precision for analog input records
   * You could calculate a good number for these based on the ADC resolution, but really a precision of `3` would probably be fine
* Additionally, deadband settings for monitoring and archiving should probably be set
   * This is a bit tangential so it's a topic for another issue (https://epics.anl.gov/base/R7-0/6-docs/aiRecord.html ; see `Monitor Parameters`)

**Comment by JJL772** [comment]
Thanks Ken, I don't know why I set PREC to default to 0 tbh, might've been something I overlooked! I'll also have a look at setting the monitoring settings.

**Comment by JJL772** [comment]
monitor parameters have been addressed in #40 and PREC defaults were addressed in #39
