### ISSUE TITLE
ADEL/MDEL Defaults

### ISSUE THREAD

**Issue by slactjohnson** [slaclab/epics-ek9000#62]
We recently moved from R1.3.2 to R1.7.1 for all our EK9000. We found that some analog sensors updated values properly, while others did not. We traced this back to a change in the default ADEL and MDEL fields. These are set to 0.03 by default in the latest release (example terminal: EL3174), while in older releases these were not set. This cause confusion with sensors that have conversions resulting in values less than 0.03 (such as power meters that do not actively have signal on them. 

I think that the ADEL/MDEL fields should be restored to the default of 0,0, or this should be a configurable parameter as part of the child IOC instantiation.

**Comment by JJL772** [comment]
Sounds good to me.

Do you think it would be desirable to provide defaults, i.e.
```
field(ADEL, "$(ADEL=0.03)")
```

That would allow for the following to be done:
```
dbLoadRecords("EL3004.template", "ADEL=0,MDEL=0,...") # Or omit ADEL/MDEL entirely for a default of 0.03
```

I'm also fine reverting ADEL/MDEL back to 0 by default if it's too much of a landmine.

**Comment by slactjohnson** [comment]
Personally, I would prefer that the default is 0.0 (always post monitors/archive) and provide a handle like you described to change the ADEL/MDEL fields if desired. So I think something like this would work with Mike's preprocessor: 
`field(ADEL, "$(ADEL)")
field(MDEL, "$(MDEL)")`
and
`dbLoadRecords("EL3004.template", "ADEL=$$IF(ADEL,$$ADEL,0.0),MDEL=$$IF(MDEL,$$MDEL,0.0),,...")`
with this in the child IOC:
`TERMINAL_N_AO(EK9000="...",RECORD="...",TYPE="EL3174",SLAVE=1,CHANNELS=4,ADEL=0.03,MDEL=0.03)`

That would give you the default of 0.0 (reasonable in my opinion) with an easy handle in the child IOC to set this on a per-terminal basis.
