### ISSUE TITLE
Device timeout and slow processing

### ISSUE THREAD

**Issue by sfsyunus** [slaclab/epics-ek9000#7]
Device times out periodically and causes ADC values to go to max raw counts, and causes DAC value to go to zero. 
	- Seems to be caused by a fast scan rate on PVs (defaults to 0.1s)
	- Behavior is erratic, non-periodic, and has different time intervals across different systems
	- Current solution: set scan rate to 1Hz (in iocsh), set watchdog timeout to 60s (in web interface), set Fallback mode to "Freeze" (in web interface)
		- Not sure what the effects of the watchdog timeout are, I may be misinterpreting that
		- The Fallback mode - "Freeze" is supposed to retain the last know values of registers instead of resetting them to max or zero, but this doesn't seem to work correctly every time
		- Setting scan to 1Hz has helped and we are no longer seeing these timeouts
			- PVs that aren't being used or are set points have been set to "Passive". 
			- The system where we see this issue (all of them) have between 8-300 PVs scanning at 10Hz which causes this issue, the lower is end of PV counts is quite low
			- Modbus is slow but shouldn't be that slow, compare to BK9000 where this issue is not seen (AIN proc at .1s with many more PVs per device)
		- *.SCAN field needs to be autosaved for all PVs

**Comment by JJL772** [comment]
Fixes applied back in June resolved this issue. PDOs were not being mapped correctly on a couple terminals which resulted in OOB reads which result in PV processing time going way up, I think the ek9k sends a slow error response or something, I don't know. This also fills up the processing queue.
