### ISSUE TITLE
Req: Device support addition

### ISSUE THREAD

**Issue by sfsyunus** [slaclab/epics-ek9000#8]
Adding device support for:
	- EL4104
	- EL4134
	- EL4114
	- EL3681
	- EL3314
	- EL3318
First 4 modules have existing support in /reg/g/pcds/epics/R7.0.2-2.0/modules/ek9000/R1.2.0-0.1.0, see related issue #6 where input output links are broken for latest device support

**Comment by JJL772** [comment]
Done in latest pre-release
